@startuml
scale 2
left to right direction
skinparam packageStyle rect
actor customer
actor customer2
rectangle checkout {
    customer -- (checkout)
    (checkout).> (payment): include
    (help).> (checkout): extend
    (checkou) -- customer2
}
@enduml